import { useState } from "react";
import { ArrowUpRight, BookOpen, Cloud, Download, ExternalLink, GitBranch, Link as LinkIcon, Mail, MessageCircle, ShieldCheck, Terminal } from "lucide-react";
import { motion } from "framer-motion";
import { Navbar } from "./components/Navbar";
import { ProjectCard, ProjectModal } from "./components/ProjectCard";
import { SectionHeading } from "./components/SectionHeading";
import { SkillCard } from "./components/SkillCard";
import { projects, type Project } from "./data/projects";
import { skillGroups } from "./data/skills";

const reveal = { hidden: { opacity: 0, y: 18 }, visible: { opacity: 1, y: 0 } };

function App() {
  const [selectedProject, setSelectedProject] = useState<Project | null>(null);
  const journey = ["2022", "Software Engineering", "Web Development", "Linux & Cloud", "Docker & CI/CD", "Kubernetes", "Helm + k3s", "Observability", "DevOps / DevSecOps"];
  return <div className="site-shell"><Navbar /><main>
    <section id="home" className="hero"><div className="hero-grid" /><div className="container hero-inner"><motion.div initial="hidden" animate="visible" variants={reveal} transition={{ duration: .6 }} className="hero-copy"><p className="eyebrow">$ whoami</p><h1>Bilal Ahmed</h1><h2>DevOps Engineer</h2><p className="hero-specialization">Cloud & DevSecOps <span>·</span> Kubernetes <span>·</span> CI/CD <span>·</span> Infrastructure <span>·</span> Observability</p><p className="hero-lede">I build, automate, deploy, and monitor cloud-native infrastructure with a focus on reliability, security, and continuous delivery.</p><div className="button-row"><a className="primary-button" href="#projects">View projects <ArrowUpRight size={16} /></a><a className="secondary-button" href="https://github.com/Bilaal-Ahmed" target="_blank" rel="noreferrer"><GitBranch size={16} /> GitHub</a></div><p className="availability"><i /> Open to DevOps opportunities</p></motion.div><motion.div initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} transition={{ duration: .6, delay: .15 }} className="hero-console"><div className="console-header"><span><i /><i /><i /></span><small>bilal@devops: ~/portfolio</small><Terminal size={15} /></div><div className="console-body"><p><span className="prompt">$</span> kubectl get systems</p><div className="console-table"><span>NAME</span><span>STATUS</span><span>FOCUS</span><strong>cloud-infra</strong><em>ready</em><strong>kubernetes</strong><em>ready</em><strong>observability</strong><em>ready</em></div><p className="console-cursor"><span className="prompt">$</span> <b>build</b> reliability --continuous</p></div><div className="console-footer"><Cloud size={14} /> pipeline health <span>100%</span></div></motion.div></div></section>
    <section id="about" className="section"><div className="container split-section"><motion.div initial="hidden" whileInView="visible" viewport={{ once: true, margin: "-80px" }} variants={reveal} transition={{ duration: .5 }}><SectionHeading eyebrow="01 / ABOUT" title="Engineering with an operator's mindset." /><p className="body-copy">I am a Software Engineering student focused on DevOps, Cloud, DevSecOps, Kubernetes, CI/CD, and observability. My work is grounded in practical learning and hands-on infrastructure rather than years of professional experience.</p><p className="body-copy">My direction has evolved from <strong>Software Engineering → Web Development → Linux & Cloud → Docker → CI/CD → Kubernetes → Helm/k3s → Observability → DevOps/DevSecOps.</strong></p></motion.div><div className="about-terminal"><div><span className="prompt">$</span> cat focus.txt</div><p>build systems that are</p><strong>repeatable.</strong><strong>secure.</strong><strong>observable.</strong><div className="terminal-line"><span className="prompt">$</span> <span className="cursor" /></div></div></div></section>
    <section id="skills" className="section section-muted"><div className="container"><SectionHeading eyebrow="02 / TOOLBOX" title="Infrastructure, end to end." description="The technologies I use to move from a local build to a monitored, secured workload." /><div className="skills-grid">{skillGroups.map((group) => <SkillCard key={group.category} group={group} />)}</div></div></section>
    <section id="projects" className="section"><div className="container"><SectionHeading eyebrow="03 / SELECTED WORK" title="Proof over promises." description="Projects built around delivery, orchestration, security boundaries, and operational visibility." /><div className="projects-grid">{projects.map((project) => <ProjectCard key={project.number} project={project} onOpen={setSelectedProject} />)}</div></div></section>
    <section id="journey" className="section section-muted"><div className="container"><SectionHeading eyebrow="04 / CAREER JOURNEY" title="Software engineering to DevOps." /><div className="journey-track">{journey.map((step, index) => <div className={`journey-step ${index === 0 ? "year" : ""}`} key={step}><span>{index === 0 ? "" : String(index).padStart(2, "0")}</span><strong>{step}</strong>{index < journey.length - 1 && <b>↓</b>}</div>)}</div></div></section>
    <section id="education" className="section"><div className="container"><SectionHeading eyebrow="05 / EDUCATION" title="Foundations that keep compounding." /><div className="education-grid"><article className="education-card"><BookOpen size={22} /><div><p className="card-kicker">2022 — 2026</p><h3>BS Software Engineering</h3><p>University of Mianwali</p><p>Mianwali</p><p>CGPA: 2.83 / 4.00</p></div></article><article className="education-card"><BookOpen size={22} /><div><p className="card-kicker">2020 — 2022</p><h3>HSSC - Pre - Engineering</h3><p>The Superior Group of Colleges. Quaidabad</p><p>Marks: 815 / 1100</p></div></article><article className="education-card"><BookOpen size={22} /><div><p className="card-kicker">2018 — 2020</p><h3>SSC - Matriculation</h3><p>Governament High School Shadia, Mianwali</p><p>Marks: 911 / 1100</p></div></article><article className="education-card subtle"><ShieldCheck size={22} /><div><p className="card-kicker">8 / 8 COURSES COMPLETED</p><h3>Google UX Design Professional Certificate</h3><p>Coursera</p></div></article></div></div></section>
    <section className="resume-band"><div className="container resume-inner"><div><p className="eyebrow">NEXT ARTIFACT</p><h2>Want to see the complete background?</h2></div><div className="button-row resume-actions"><a className="primary-button" href="/BILAL%20AHMED%20DevOps.pdf" target="_blank" rel="noreferrer">View resume <ExternalLink size={16} /></a><a className="secondary-button" href="/BILAL%20AHMED%20DevOps.pdf" download="BILAL AHMED DevOps.pdf"><Download size={16} /> Download resume</a></div></div></section>
    <section id="contact" className="section contact-section"><div className="container contact-inner"><SectionHeading eyebrow="06 / CONTACT" title="Let's build something reliable." description="Open to DevOps, Cloud, DevSecOps, and SRE opportunities." /><div className="contact-links"><a href="mailto:mr.bilal.ahmed281@gmail.com"><Mail size={18} /><span>Email</span><ArrowUpRight size={15} /></a><a href="https://www.linkedin.com/in/bilal-ahmed-26513b296/" target="_blank" rel="noreferrer"><LinkIcon size={18} /><span>LinkedIn</span><ArrowUpRight size={15} /></a><a href="https://github.com/Bilaal-Ahmed" target="_blank" rel="noreferrer"><GitBranch size={18} /><span>GitHub</span><ArrowUpRight size={15} /></a><a href="https://wa.me/923187584281" target="_blank" rel="noreferrer"><MessageCircle size={18} /><span>WhatsApp: +923187584281</span><ArrowUpRight size={15} /></a></div></div></section>
  </main><footer><div className="container footer-inner"><div><a className="footer-brand" href="#home">Bilal Ahmed</a><p>DevOps Engineer</p></div><p>Cloud & DevSecOps <span>·</span> Kubernetes <span>·</span> CI/CD <span>·</span> Observability</p><small>© {new Date().getFullYear()} Bilal Ahmed</small></div></footer>{selectedProject && <ProjectModal project={selectedProject} onClose={() => setSelectedProject(null)} />}</div>;
}

export default App;